(function(){
 const API="https://api.betheltradingtechnologies.com/public/reviews";
 const root=document.createElement("section");
 root.className="bethel-reviews";
 root.id="visitor-reviews";
 root.innerHTML=`<div class="bethel-reviews-card"><div class="bethel-reviews-head"><div><h2>Visitor Reviews</h2><div class="bethel-review-score"><span id="bethel-review-average">No ratings yet</span> <span class="bethel-review-stars">★★★★★</span></div></div><div id="bethel-review-count"></div></div><div id="bethel-review-grid" class="bethel-review-grid"></div><h3>Leave a review</h3><form id="bethel-review-form" class="bethel-review-form"><input name="display_name" maxlength="80" required placeholder="Your name"><select name="rating" required aria-label="Star rating"><option value="">Choose rating</option><option value="5">★★★★★ 5 stars</option><option value="4">★★★★☆ 4 stars</option><option value="3">★★★☆☆ 3 stars</option><option value="2">★★☆☆☆ 2 stars</option><option value="1">★☆☆☆☆ 1 star</option></select><textarea name="review" maxlength="800" required placeholder="Share your experience"></textarea><input name="email" type="email" maxlength="254" placeholder="Email (optional, never shown publicly)"><button type="submit">Submit review</button><div id="bethel-review-message" class="bethel-review-message">Reviews are moderated before publication.</div></form></div>`;
 const contact=document.getElementById("contact");
 if(contact&&contact.parentNode)contact.parentNode.insertBefore(root,contact);else document.body.appendChild(root);
 const grid=root.querySelector("#bethel-review-grid"),avg=root.querySelector("#bethel-review-average"),count=root.querySelector("#bethel-review-count"),form=root.querySelector("#bethel-review-form"),msg=root.querySelector("#bethel-review-message");
 const esc=s=>String(s||"");
 function stars(n){return "★".repeat(Number(n)||0)+"☆".repeat(5-(Number(n)||0));}
 async function load(){try{const r=await fetch(API,{cache:"no-store",headers:{Accept:"application/json"}});if(!r.ok)throw new Error();const d=await r.json();avg.textContent=d.review_count?`${Number(d.average_rating).toFixed(1)} / 5`:"No ratings yet";count.textContent=`${d.review_count||0} approved review${d.review_count===1?"":"s"}`;grid.innerHTML="";(d.reviews||[]).forEach(v=>{const item=document.createElement("article");item.className="bethel-review-item";const strong=document.createElement("strong");strong.textContent=esc(v.display_name);const star=document.createElement("div");star.className="bethel-review-stars";star.textContent=stars(v.rating);const p=document.createElement("p");p.textContent=esc(v.review);item.append(strong,star,p);grid.appendChild(item);});}catch(_){count.textContent="Reviews temporarily unavailable";}}
 form.addEventListener("submit",async e=>{e.preventDefault();const button=form.querySelector("button");button.disabled=true;msg.textContent="Submitting…";const fd=new FormData(form);const payload={display_name:fd.get("display_name"),rating:Number(fd.get("rating")),review:fd.get("review"),email:fd.get("email")||null};try{const r=await fetch(API,{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(typeof d.detail==="string"?d.detail:"Review could not be submitted");msg.textContent=d.message||"Thank you. Your review is awaiting moderation.";form.reset();}catch(err){msg.textContent=err.message||"Review could not be submitted.";}finally{button.disabled=false;}});
 load();
})();